### ISSUE TITLE
Implementation detail of extract_feat function

### ISSUE THREAD

**Issue by Yanyirong** [facebookresearch/NeRF-Det#12]
In this extract_feat function.The 'densitys' variable seems to be an empty list.Why does it appear here? Is it because there are some expanded functions in future work?

https://github.com/facebookresearch/NeRF-Det/blob/445999690d0924a750e9f8782b0fa1124295e9b0/mmdet3d/models/detectors/nerfdet.py#L269

**Comment by chenfengxu714** [comment]
Feel free to repolish the code. sorry that I may miss these details when I cleaned the code.
