### ISSUE TITLE
Help: why the depth divided by 1000

### ISSUE THREAD

**Issue by OrangeSodahub** [facebookresearch/NeRF-Det#3]
Thanks for your work. I wonder why here divide the depth value by 1000:

https://github.com/facebookresearch/NeRF-Det/blob/8684e1f856d3005754c4eed8c0a4e6b1b1ab4948/mmdet3d/datasets/pipelines/multi_view.py#L103

**Comment by chenfengxu714** [comment]
It is because Scannet depth map is in mm unit metric, we transform it to meter.

**Comment by OrangeSodahub** [comment]
Thanks. You mean the png files extracted from .sens files? I fetched one of them, and see the values might not be in mm unit metric:

![image](https://github.com/facebookresearch/NeRF-Det/assets/54439582/f1bc1c76-88dd-4431-98db-aff525f19f56)

**Comment by OrangeSodahub** [comment]
cc @chenfengxu714

**Comment by chenfengxu714** [comment]
I remembered that I extracted the depth maps via https://github.com/SamsungLabs/imvoxelnet/blob/master/data/scannet/extract_posed_images.py#L99
and my depth map is in mm unit. It seems that yours are in meter unit. If so you can visualize it to double-check and just remove /1000 to fit your case.

**Comment by OrangeSodahub** [comment]
@chenfengxu714 That's weird, I used the same script as yours. are the values of yours at 1e3~1e4 level?

**Comment by chenfengxu714** [comment]
Hi, Sorry that I can not access to the machines I worked on in Meta so can’t check it for you. I remembered my depth images are in mm unit. Some also talked about it https://github.com/ScanNet/ScanNet/issues/17.

I am not sure why we are different but I think you can just modify your code based on your cases. It should work too.

**Comment by OrangeSodahub** [comment]
Is this difference caused by the version of python? I used python3, you used python2

**Comment by HCaelrs** [comment]
In source code, it use 'from PIL import Image'. It may caused by the cv2.imread(). 
![image](https://github.com/facebookresearch/NeRF-Det/assets/53749904/d61d81cc-d9fe-4f49-9c6f-72ab4a56881f)

**Comment by OrangeSodahub** [comment]
@HCaelrs Yeah, true, I just found this too, thanks for your suggestion.

**Comment by OrangeSodahub** [comment]
@HCaelrs Hi, another point I'm confused is:
https://github.com/facebookresearch/NeRF-Det/blob/8684e1f856d3005754c4eed8c0a4e6b1b1ab4948/configs/nerfdet/nerfdet_res50_2x_low_res.py#L34
What is it?

**Comment by HCaelrs** [comment]
Maybe you can see [here](https://github.com/facebookresearch/NeRF-Det/blob/8684e1f856d3005754c4eed8c0a4e6b1b1ab4948/mmdet3d/models/model_utils/render_ray.py#L38). It limits the whole scene in the range of aabb.

**Comment by HCaelrs** [comment]
Maybe you can see [here](https://github.com/facebookresearch/NeRF-Det/blob/8684e1f856d3005754c4eed8c0a4e6b1b1ab4948/mmdet3d/models/model_utils/render_ray.py#L38). It limits the whole scene in the range of aabb.

**Comment by OrangeSodahub** [comment]
@HCaelrs Yeah I know, but this is just defined by you? can it be changed? BTW, I want to check the coordinates of the camera and global, x-right, y-up, z-front for camera, x-right, y-up, z-front for global, right?

**Comment by chenfengxu714** [comment]
Hi @OrangeSodahub, you can change the aabb size by checking the whole-dataset bounding box. However different rooms have different sizes so it is not suitable to set a fixed aabb size, this is why our default setting is image-mode, in which we directly sample features from images instead of volumes.
