### ISSUE TITLE
Depth makes the performance much worse

### ISSUE THREAD

**Issue by HCaelrs** [facebookresearch/NeRF-Det#5]
![image](https://github.com/facebookresearch/NeRF-Det/assets/53749904/2a378ce6-a9e9-4d14-ba8f-ad9627dc9871)
I ran the config with the [depth](https://github.com/facebookresearch/NeRF-Det/blob/main/configs/nerfdet/nerfdet_res50_2x_low_res_depth_sp.py) simply use `bash tools/dist_train.sh configs/nerfdet/nerfdet_res50_2x_low_res_depth_sp.py 4 ` , but I found its performance is much worse than without depth.
Do you have idea what caused this? Or maybe need some other steps?
Thank you!

**Comment by chenfengxu714** [comment]
Oh, it is strange, seems something is wrong and not converging. Could you also have a try for the res101-depth-sp setting? This should reproduce the results I release. It should be the same config to res50-depth-sp-setting except the model. Thanks!

**Comment by HCaelrs** [comment]
Ok, I’ll try res101-depth-sp. I tried the res101_2x_orign_res_depth_sp, I didn't finish the training. Because it seems to have performance as bad as res50-depth-sp at maybe 6 or 7 epoch.

**Comment by HCaelrs** [comment]
Sorry, it's my fault! I found that I did not rewrite the pkl file after re extracting the posed image with depth! Thanks for your reply!

**Comment by mrsempress** [comment]
Could you share the pkl files? If so, we would appreciate it.
